name: Build Release

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Gofmt
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then gofmt -d . && exit 1; fi

      - name: Go mod download
        run: go mod download
        working-directory: src/

      - name: Go Vet
        run: go vet ./...
        working-directory: src/

      - name: Go Build
        run: go build .
        working-directory: src/

      - name: Go Test
        run: go test ./...
        working-directory: src/

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build container image
        run: sam build --use-container

      - name: Deploy function code
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name go-lambda-template --s3-bucket srakjfkasnfakjf --capabilities CAPABILITY_IAM --region eu-west-1
