name: Run Tests

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '!v*'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Gofmt
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then gofmt -d . && exit 1; fi

      - name: Go mod download
        run: go mod download
        working-directory: src/

      - name: Go Vet
        run: go vet ./...
        working-directory: src/

      - name: Go Build
        run: go build .
        working-directory: src/

      - name: Go Test
        run: go test ./...
        working-directory: src/
